### ISSUE TITLE
Clarification request

### ISSUE THREAD

**Issue by robmarkcole** [chaisaeng/Tensorflow-1.13.2-alpine-armv7#1]
The method `1. logon to raspberry pi with user pi` indicates you are running HA in docker on a regular (raspbian) pi, not using HassOS, correct?

**Comment by chaisaeng** [comment]
I run it on raspberry pi under docker on raspbian lite no desktop just using ssh to do everything on the pi. to install this pre-built tensorflow. you need to use command docker exec -it <your homeassistant container name> /bin/bash then after ward you can use pip install tensorflow-1.13.2-cp37-cp37m-linux_armv7l.whl and other dependencies whl

**Comment by chaisaeng** [comment]
The answer to the issue is yes it running on a regular raspbian not hassos. just create a docker-compose.yaml file then start it with docker-compose up -d on the raspberry pi under user pi.
